import Link from "next/link";
import { notFound } from "next/navigation";
import { Mail, MapPin, Phone } from "lucide-react";
import { requireTenantContext } from "@/lib/authz/tenant-context";
import { formatDate, orderStageClasses, orderStageLabels } from "@/lib/presentation/orders";
import { getCustomer, listCustomerOrders } from "@/modules/customers/queries";

export default async function CustomerPage({ params }: { params: Promise<{ customerId: string }> }) {
  const [{ customerId }, context] = await Promise.all([params, requireTenantContext()]);
  const [customer, customerOrders] = await Promise.all([getCustomer({ organizationId: context.organizationId, customerId }), listCustomerOrders({ organizationId: context.organizationId, customerId })]);
  if (!customer) notFound();
  return <><Link href="/app/customers" className="text-sm text-muted-foreground">← Клиенти</Link><div className="mt-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold text-primary">{customer.kind === "company" ? "Фирма" : "Клиент"}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{customer.name}</h1><p className="mt-1 text-muted-foreground">{customer.companyName}</p></div><Link href={`/app/orders/new?customer=${customer.id}`} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">+ Нова поръчка</Link></div><div className="mt-7 grid gap-5 lg:grid-cols-[340px_1fr]"><aside className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">Контакти</h2><div className="mt-5 space-y-4 text-sm">{customer.email && <a href={`mailto:${customer.email}`} className="flex gap-3"><Mail className="size-4 text-muted-foreground" />{customer.email}</a>}{customer.phone && <a href={`tel:${customer.phone}`} className="flex gap-3"><Phone className="size-4 text-muted-foreground" />{customer.phone}</a>}{customer.address && <p className="flex gap-3"><MapPin className="size-4 shrink-0 text-muted-foreground" />{customer.address}</p>}</div>{customer.notes && <div className="mt-6 border-t pt-5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Бележки</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{customer.notes}</p></div>}</aside><section className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="border-b px-5 py-4"><h2 className="font-semibold">Поръчки</h2></div>{customerOrders.length ? <div className="divide-y">{customerOrders.map(order => <Link key={order.id} href={`/app/orders/${order.id}`} className="grid gap-2 px-5 py-4 hover:bg-muted/50 sm:grid-cols-[120px_1fr_150px_100px] sm:items-center"><span className="font-mono text-xs">{order.orderNumber}</span><span className="font-medium">{order.title}</span><span className={`w-fit rounded-full px-2 py-1 text-xs font-semibold ${orderStageClasses[order.stage]}`}>{orderStageLabels[order.stage]}</span><span className="text-sm text-muted-foreground sm:text-right">{formatDate(order.updatedAt)}</span></Link>)}</div> : <p className="px-5 py-12 text-center text-sm text-muted-foreground">Все още няма поръчки.</p>}</section></div></>;
}
