import { Field, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { ActionForm, ActionSubmit } from "@/components/workspace/action-form";
import { FilterSelect } from "@/components/workspace/filter-select";
import { addInstallmentAction, addMilestoneAction, correctReceiptAction, recordReceiptAction, resolvePaymentDisputeAction, updateChangeWorkAction, updateMilestoneAction } from "@/modules/projects/operations";
import { getProjectState } from "@/modules/projects/state";

type State = NonNullable<Awaited<ReturnType<typeof getProjectState>>>;
const paymentKinds = [{ value: "deposit", label: "Капаро" }, { value: "progress", label: "Междинно" }, { value: "final", label: "Окончателно" }, { value: "other", label: "Друго" }];

export function ProjectControls({ state, canManage, canRecordPayments, canUpdateStages, disputes, section = "all" }: {
  state: State; canManage: boolean; canRecordPayments: boolean; canUpdateStages: boolean;
  disputes: Array<{ id: string; reason: string; receiptId: string }>;
  section?: "all" | "work" | "payments";
}) {
  const projectId = state.project.id;
  const today = new Date().toISOString().slice(0, 10);
  return <div className="space-y-5">
    {(section === "all" || section === "work") && canUpdateStages && state.milestones.length ? <section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Отчети етап</h2><div className="mt-3 divide-y">{state.milestones.map((item) => <ActionForm key={item.id} action={updateMilestoneAction} success="Етапът е обновен" className="flex flex-wrap items-end justify-between gap-3 py-3"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="milestoneId" value={item.id} /><p className="min-w-40 flex-1 font-medium">{item.title}</p><Field className="w-44"><FieldLabel>Статус</FieldLabel><FilterSelect name="status" value={item.status} options={[{ value: "planned", label: "Предстои" }, { value: "in_progress", label: "В работа" }, { value: "completed", label: "Завършен" }]} /></Field><ActionSubmit variant="outline">Запази</ActionSubmit></ActionForm>)}</div><p className="mt-3 text-xs text-muted-foreground">Завършването не отбелязва автоматично получено плащане.</p></section> : null}
    {(section === "all" || section === "work") && canUpdateStages && state.changes.length ? <section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Допълнителна работа</h2><div className="mt-3 divide-y">{state.changes.map((change) => <ActionForm key={change.id} action={updateChangeWorkAction} success="Статусът на работата е обновен" className="flex flex-wrap items-end justify-between gap-3 py-3"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="changeOrderId" value={change.id} /><p className="min-w-40 flex-1 font-medium">{change.title}</p><Field className="w-44"><FieldLabel>Статус</FieldLabel><FilterSelect name="workStatus" value={change.workStatus} options={[{ value: "not_started", label: "Предстои" }, { value: "scheduled", label: "Планирана" }, { value: "in_progress", label: "В работа" }, { value: "completed", label: "Завършена" }]} /></Field><ActionSubmit variant="outline">Запази</ActionSubmit></ActionForm>)}</div></section> : null}
    {(section === "all" || section === "work") && canManage ? <section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Добави етап</h2><ActionForm action={addMilestoneAction} success="Етапът е добавен" className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="projectId" value={projectId} /><Field><FieldLabel htmlFor="milestone-title">Име</FieldLabel><Input id="milestone-title" name="title" required minLength={2} placeholder="Напр. Монтаж" className="h-10" /></Field><Field><FieldLabel htmlFor="milestone-date">Срок</FieldLabel><Input id="milestone-date" type="date" name="dueOn" required className="h-10" /></Field><Field className="sm:col-span-2"><FieldLabel>Работа</FieldLabel><FilterSelect name="changeOrderId" value="none" options={[{ value: "none", label: "Основна работа" }, ...state.changes.map((change) => ({ value: change.id, label: change.title }))]} /></Field><ActionSubmit className="sm:col-span-2">Добави етап</ActionSubmit></ActionForm></section> : null}
    {(section === "all" || section === "payments") && canManage ? <section className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Планирай вноска</h2><ActionForm action={addInstallmentAction} success="Вноската е планирана" className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="projectId" value={projectId} /><Field><FieldLabel htmlFor="installment-title">Име</FieldLabel><Input id="installment-title" name="title" required minLength={2} placeholder="Напр. Капаро" className="h-10" /></Field><Field><FieldLabel>Вид</FieldLabel><FilterSelect name="kind" value="deposit" options={paymentKinds} /></Field><Field><FieldLabel htmlFor="installment-amount">Сума</FieldLabel><Input id="installment-amount" type="number" name="amount" min="0.01" step="0.01" required className="h-10" /></Field><Field><FieldLabel htmlFor="installment-date">Падеж</FieldLabel><Input id="installment-date" type="date" name="dueOn" required className="h-10" /></Field><Field className="sm:col-span-2"><FieldLabel>Етап</FieldLabel><FilterSelect name="milestoneId" value="none" options={[{ value: "none", label: "Без обвързан етап" }, ...state.milestones.map((item) => ({ value: item.id, label: item.title }))]} /></Field><ActionSubmit className="sm:col-span-2">Планирай</ActionSubmit></ActionForm></section> : null}
    {(section === "all" || section === "payments") && canRecordPayments ? <section id="record-payment" className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Запиши получено плащане</h2><ActionForm action={recordReceiptAction} success="Плащането е записано" className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="projectId" value={projectId} /><Field><FieldLabel>Вноска</FieldLabel><FilterSelect name="installmentId" value="none" options={[{ value: "none", label: "Без обвързана вноска" }, ...state.installments.map((item) => ({ value: item.id, label: item.title }))]} /></Field><Field><FieldLabel>Вид</FieldLabel><FilterSelect name="kind" value="deposit" options={paymentKinds} /></Field><Field><FieldLabel htmlFor="receipt-amount">Получена сума</FieldLabel><Input id="receipt-amount" type="number" name="amount" min="0.01" step="0.01" required className="h-10" /></Field><Field><FieldLabel htmlFor="receipt-date">Дата</FieldLabel><Input id="receipt-date" type="date" name="receivedOn" defaultValue={today} required className="h-10" /></Field><Field><FieldLabel>Метод</FieldLabel><FilterSelect name="method" value="bank" options={[{ value: "bank", label: "Банков превод" }, { value: "cash", label: "В брой" }, { value: "card", label: "Карта" }, { value: "other", label: "Друго" }]} /></Field><Field><FieldLabel htmlFor="receipt-note">Бележка</FieldLabel><Input id="receipt-note" name="note" maxLength={500} className="h-10" /></Field><ActionSubmit className="sm:col-span-2">Запиши плащането</ActionSubmit></ActionForm>
      {state.receipts.some((item) => Number(item.amount) > 0 && !item.correctionOfId) ? <div className="mt-6 border-t pt-5"><h3 className="font-semibold">Коригирай запис</h3><div className="mt-2 divide-y">{state.receipts.filter((item) => Number(item.amount) > 0 && !item.correctionOfId).map((item) => <ActionForm key={item.id} action={correctReceiptAction} success="Плащането е коригирано" className="flex flex-wrap items-end gap-3 py-3"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="receiptId" value={item.id} /><span className="min-w-36 py-2 text-sm">{item.receivedOn} · {item.amount}</span><Field className="min-w-32 flex-1"><FieldLabel>Нова сума</FieldLabel><Input type="number" name="amount" step="0.01" min="0.01" required className="h-10" /></Field><Field className="min-w-48 flex-1"><FieldLabel>Причина</FieldLabel><Input name="reason" required minLength={3} className="h-10" /></Field><ActionSubmit variant="outline">Коригирай</ActionSubmit></ActionForm>)}</div></div> : null}
      {disputes.length ? <div className="mt-6 border-t pt-5"><h3 className="font-semibold">Оспорени плащания</h3><div className="mt-2 divide-y">{disputes.map((item) => <ActionForm key={item.id} action={resolvePaymentDisputeAction} success="Спорът е разрешен" className="flex flex-wrap items-end gap-3 py-3"><input type="hidden" name="projectId" value={projectId} /><input type="hidden" name="disputeId" value={item.id} /><span className="min-w-40 flex-1 text-sm">{item.reason}</span><Field className="min-w-48 flex-1"><FieldLabel>Решение</FieldLabel><Input name="resolution" required minLength={3} className="h-10" /></Field><ActionSubmit variant="outline">Разреши</ActionSubmit></ActionForm>)}</div></div> : null}
    </section> : null}
  </div>;
}
