import Link from "next/link";
import { Search, UserPlus } from "lucide-react";
import { requireTenantContext } from "@/lib/authz/tenant-context";
import { listCustomers } from "@/modules/customers/queries";

export default async function CustomersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const [{ q }, context] = await Promise.all([searchParams, requireTenantContext()]);
  const customers = await listCustomers({ organizationId: context.organizationId, query: q });
  return <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-primary">CRM</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Клиенти</h1><p className="mt-2 text-muted-foreground">Контакти и история на всички поръчки.</p></div><Link href="/app/customers/new" className="inline-flex h-10 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><UserPlus className="size-4" />Нов клиент</Link></div><form className="mt-7 flex max-w-lg items-center gap-2 rounded-xl border bg-card px-3 shadow-sm"><Search className="size-4 text-muted-foreground" /><input name="q" defaultValue={q} placeholder="Търси по име, телефон или имейл" className="h-11 flex-1 bg-transparent text-sm outline-none" /></form><section className="mt-5 overflow-hidden rounded-2xl border bg-card shadow-sm">{customers.length ? <div className="divide-y">{customers.map(customer => <Link key={customer.id} href={`/app/customers/${customer.id}`} className="grid gap-2 px-5 py-4 hover:bg-muted/50 sm:grid-cols-[1fr_1fr_1fr_120px] sm:items-center"><div><p className="font-medium">{customer.name}</p><p className="text-xs text-muted-foreground">{customer.kind === "company" ? customer.companyName || "Фирма" : "Физическо лице"}</p></div><span className="text-sm text-muted-foreground">{customer.email || "—"}</span><span className="text-sm text-muted-foreground">{customer.phone || "—"}</span><span className="text-sm font-medium text-primary sm:text-right">Отвори →</span></Link>)}</div> : <div className="py-16 text-center"><p className="font-medium">Няма намерени клиенти</p><p className="mt-1 text-sm text-muted-foreground">Добави първия клиент, за да създадеш поръчка.</p></div>}</section></>;
}
