"use client";

import { useEffect, useRef, useState, useTransition } from "react";
import { Check, LoaderCircle, Plus, Trash2 } from "lucide-react";
import { saveOrderDraftAction } from "@/modules/orders/actions";

type Field = { stableKey: string; sectionKey: string; sectionLabel: string; label: string; fieldType: string; unit?: string | null; required: boolean; optionsJson?: string[] | null };
type LineItem = { id: string; description: string; quantity: string; unit: string; unitPrice: string };
type Commercial = { currency?: string; totalMinor?: string; depositRequiredMinor?: string; notes?: string; items?: LineItem[] };

function toMinor(value: string) { const normalized = value.replace(",", ".").trim(); if (!normalized) return "0"; const [whole, fraction = ""] = normalized.split("."); return `${whole || "0"}${fraction.padEnd(2, "0").slice(0, 2)}`.replace(/^0+(?=\d)/, ""); }
function fromMinor(value: unknown) { const raw = String(value ?? "0").padStart(3, "0"); return `${raw.slice(0, -2)}.${raw.slice(-2)}`; }
function lineTotal(item: LineItem) { const quantity = Number(item.quantity.replace(",", ".")) || 0; const price = Number(item.unitPrice.replace(",", ".")) || 0; return quantity * price; }

export function SpecificationEditor({ orderId, initialRevision, initialValues, initialCommercial, fields }: { orderId: string; initialRevision: number; initialValues: Record<string, unknown>; initialCommercial: Commercial; fields: Field[] }) {
  const [values, setValues] = useState(initialValues); const [revision, setRevision] = useState(initialRevision);
  const [commercial, setCommercial] = useState<Commercial>({ ...initialCommercial, items: initialCommercial.items ?? [] });
  const [status, setStatus] = useState("Всички промени са запазени"); const [pending, startTransition] = useTransition(); const first = useRef(true); const revisionRef = useRef(initialRevision);
  const items = commercial.items ?? [];
  const computedTotal = items.reduce((sum, item) => sum + lineTotal(item), 0);
  useEffect(() => { if (first.current) { first.current = false; return; } setStatus("Запазване…"); const timer = window.setTimeout(() => { startTransition(async () => { const nextCommercial = { ...commercial, totalMinor: toMinor(computedTotal ? computedTotal.toFixed(2) : fromMinor(commercial.totalMinor)), depositRequiredMinor: commercial.depositRequiredMinor ?? "0" }; const result = await saveOrderDraftAction({ orderId, revision: revisionRef.current, values, commercial: nextCommercial }); if (result.ok) { revisionRef.current = result.revision; setRevision(result.revision); setStatus("Всички промени са запазени"); } else setStatus(result.message); }); }, 700); return () => window.clearTimeout(timer); }, [values, commercial, computedTotal, orderId]);
  const sections = Array.from(new Map(fields.map(field => [field.sectionKey, field.sectionLabel])).entries());
  const setValue = (key: string, value: unknown) => setValues(current => ({ ...current, [key]: value }));
  const updateItem = (id: string, patch: Partial<LineItem>) => setCommercial(current => ({ ...current, items: (current.items ?? []).map(item => item.id === id ? { ...item, ...patch } : item) }));
  const input = "mt-1.5 h-10 w-full rounded-xl border bg-background px-3 text-sm outline-none focus:border-primary focus:ring-3 focus:ring-primary/15";
  return <div className="space-y-6"><div className="sticky top-16 z-20 flex items-center justify-between rounded-xl border bg-card/95 px-4 py-3 shadow-sm backdrop-blur"><p className="text-sm text-muted-foreground">Чернова · ревизия {revision}</p><span className="inline-flex items-center gap-2 text-xs text-muted-foreground">{pending ? <LoaderCircle className="size-3.5 animate-spin" /> : <Check className="size-3.5 text-emerald-600" />}{status}</span></div>
    {sections.map(([sectionKey, sectionLabel]) => <section key={sectionKey} className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="font-semibold">{sectionLabel}</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{fields.filter(f => f.sectionKey === sectionKey).map(field => {
      const value = values[field.stableKey]; const label = <>{field.label}{field.required && <span className="ml-1 text-destructive">*</span>}{field.unit && <span className="ml-1 text-muted-foreground">({field.unit})</span>}</>;
      if (field.fieldType === "long_text") return <label key={field.stableKey} className="block text-sm font-medium md:col-span-2">{label}<textarea rows={3} value={String(value ?? "")} onChange={e => setValue(field.stableKey, e.target.value)} className="mt-1.5 w-full rounded-xl border bg-background p-3 outline-none focus:border-primary focus:ring-3 focus:ring-primary/15" /></label>;
      if (field.fieldType === "boolean") return <label key={field.stableKey} className="flex items-center gap-3 rounded-xl border p-3 text-sm font-medium"><input type="checkbox" checked={Boolean(value)} onChange={e => setValue(field.stableKey, e.target.checked)} className="size-4 accent-primary" />{label}</label>;
      if (field.fieldType === "single_select") return <label key={field.stableKey} className="block text-sm font-medium">{label}<select value={String(value ?? "")} onChange={e => setValue(field.stableKey, e.target.value)} className={input}><option value="">Избери</option>{field.optionsJson?.map(option => <option key={option}>{option}</option>)}</select></label>;
      if (field.fieldType === "file" || field.fieldType === "image_gallery") return <div key={field.stableKey} className="rounded-xl border border-dashed p-4 text-sm"><p className="font-medium">{label}</p><p className="mt-1 text-muted-foreground">Добави от секцията „Файлове“ по-долу.</p></div>;
      const type = ["integer","decimal","measurement","money"].includes(field.fieldType) ? "number" : field.fieldType === "date" ? "date" : field.fieldType === "colour" ? "text" : "text";
      return <label key={field.stableKey} className="block text-sm font-medium">{label}<input type={type} value={String(value ?? "")} onChange={e => setValue(field.stableKey, e.target.value)} className={input} /></label>;
    })}</div></section>)}
    <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Оферта</h2><p className="text-sm text-muted-foreground">Ръчни позиции — без Stripe.</p></div><button type="button" onClick={() => setCommercial(current => ({ ...current, items: [...(current.items ?? []), { id: crypto.randomUUID(), description: "", quantity: "1", unit: "бр.", unitPrice: "0.00" }] }))} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold"><Plus className="size-4" />Позиция</button></div><div className="mt-5 space-y-3">{items.map(item => <div key={item.id} className="grid gap-2 rounded-xl border p-3 md:grid-cols-[1fr_90px_90px_120px_100px_36px] md:items-end"><label className="text-xs text-muted-foreground">Описание<input value={item.description} onChange={e => updateItem(item.id,{description:e.target.value})} className={input} /></label><label className="text-xs text-muted-foreground">Количество<input value={item.quantity} onChange={e => updateItem(item.id,{quantity:e.target.value})} className={input} /></label><label className="text-xs text-muted-foreground">Мярка<input value={item.unit} onChange={e => updateItem(item.id,{unit:e.target.value})} className={input} /></label><label className="text-xs text-muted-foreground">Ед. цена<input value={item.unitPrice} onChange={e => updateItem(item.id,{unitPrice:e.target.value})} className={input} /></label><p className="pb-2 text-right text-sm font-semibold">{lineTotal(item).toFixed(2)} {commercial.currency ?? "EUR"}</p><button type="button" aria-label="Изтрий позицията" onClick={() => setCommercial(current => ({...current,items:(current.items ?? []).filter(row=>row.id!==item.id)}))} className="mb-1 grid size-8 place-items-center rounded-lg text-destructive hover:bg-destructive/10"><Trash2 className="size-4" /></button></div>)}</div><div className="mt-5 grid gap-5 border-t pt-5 sm:grid-cols-2"><label className="text-sm font-medium">Изискуемо капаро<input value={fromMinor(commercial.depositRequiredMinor)} onChange={e => setCommercial(current => ({...current,depositRequiredMinor:toMinor(e.target.value)}))} inputMode="decimal" className={input} /></label><div className="rounded-xl bg-muted p-4 text-right"><p className="text-xs text-muted-foreground">Обща стойност</p><p className="mt-1 text-2xl font-semibold">{computedTotal.toFixed(2)} {commercial.currency ?? "EUR"}</p></div></div></section>
  </div>;
}
