"use server";
import { and, eq, sql } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { getDatabase } from "@/db";
import { activityEvents, installations, orders, payments, serviceRequests, warrantyItems } from "@/db/schema";
import { requireTenantContext } from "@/lib/authz/tenant-context";
import { parseMoneyToMinor } from "@/lib/money";

const orderId = z.uuid();
export async function updateOrderStageAction(formData:FormData){const id=orderId.parse(formData.get("orderId"));const stage=z.enum(["draft","awaiting_approval","approved","in_production","ready_for_installation","installed","completed","service"]).parse(formData.get("stage"));const context=await requireTenantContext();await getDatabase().transaction(async tx=>{await tx.update(orders).set({stage}).where(and(eq(orders.organizationId,context.organizationId),eq(orders.id,id)));await tx.insert(activityEvents).values({organizationId:context.organizationId,orderId:id,actorType:"user",actorUserId:context.userId,eventType:"order_stage_changed",entityType:"order",entityId:id,metadataJson:{stage}})});revalidatePath(`/app/orders/${id}`);revalidatePath("/app/orders");}

export async function recordPaymentAction(formData:FormData){const id=orderId.parse(formData.get("orderId"));const kind=z.enum(["deposit","progress","final","other"]).parse(formData.get("kind"));const amount=z.string().min(1).parse(formData.get("amount"));const currency=z.enum(["EUR","BGN"]).parse(formData.get("currency"));const note=z.string().max(500).optional().parse(formData.get("note")||undefined);const context=await requireTenantContext();const amountMinor=parseMoneyToMinor(amount,currency);if(amountMinor<=0n)throw new Error("Сумата трябва да е положителна.");await getDatabase().transaction(async tx=>{const[payment]=await tx.insert(payments).values({organizationId:context.organizationId,orderId:id,kind,amountMinor,currency,paidAt:new Date(),note,createdBy:context.userId}).returning({id:payments.id});if(kind==="deposit")await tx.update(orders).set({depositPaidMinor:sql`${orders.depositPaidMinor}+${amountMinor}`}).where(and(eq(orders.organizationId,context.organizationId),eq(orders.id,id)));await tx.insert(activityEvents).values({organizationId:context.organizationId,orderId:id,actorType:"user",actorUserId:context.userId,eventType:"payment_recorded",entityType:"payment",entityId:payment?.id,metadataJson:{kind,amountMinor:amountMinor.toString(),currency}})});revalidatePath(`/app/orders/${id}`);}

export async function scheduleInstallationAction(formData:FormData){const id=orderId.parse(formData.get("orderId"));const scheduledFor=z.iso.datetime({local:true}).parse(formData.get("scheduledFor"));const notes=z.string().max(2000).optional().parse(formData.get("notes")||undefined);const context=await requireTenantContext();await getDatabase().insert(installations).values({organizationId:context.organizationId,orderId:id,scheduledFor:new Date(scheduledFor),notes}).onConflictDoUpdate({target:installations.orderId,set:{scheduledFor:new Date(scheduledFor),notes}});revalidatePath(`/app/orders/${id}`);}

export async function completeInstallationAction(formData:FormData){const id=orderId.parse(formData.get("orderId"));const status=z.enum(["accepted","issues"]).parse(formData.get("acceptanceStatus"));const context=await requireTenantContext();await getDatabase().transaction(async tx=>{await tx.update(installations).set({installedAt:new Date(),acceptanceStatus:status}).where(and(eq(installations.organizationId,context.organizationId),eq(installations.orderId,id)));await tx.update(orders).set({stage:status==="accepted"?"installed":"service"}).where(and(eq(orders.organizationId,context.organizationId),eq(orders.id,id)));await tx.insert(activityEvents).values({organizationId:context.organizationId,orderId:id,actorType:"user",actorUserId:context.userId,eventType:"installation_completed",entityType:"installation",metadataJson:{acceptanceStatus:status}})});revalidatePath(`/app/orders/${id}`);}

export async function addWarrantyItemAction(formData:FormData){const id=orderId.parse(formData.get("orderId"));const data=z.object({name:z.string().trim().min(2).max(200),manufacturer:z.string().max(160).optional(),model:z.string().max(160).optional(),serialNumber:z.string().max(160).optional(),warrantyStart:z.union([z.literal(""),z.iso.date()]),warrantyEnd:z.union([z.literal(""),z.iso.date()])}).parse(Object.fromEntries(formData));const context=await requireTenantContext();await getDatabase().insert(warrantyItems).values({organizationId:context.organizationId,orderId:id,name:data.name,manufacturer:data.manufacturer||null,model:data.model||null,serialNumber:data.serialNumber||null,warrantyStart:data.warrantyStart||null,warrantyEnd:data.warrantyEnd||null});revalidatePath(`/app/orders/${id}`);}

export async function createServiceRequestAction(formData:FormData){const id=orderId.parse(formData.get("orderId"));const data=z.object({title:z.string().trim().min(2).max(200),description:z.string().trim().min(3).max(4000),warrantyItemId:z.union([z.literal(""),z.uuid()]).optional()}).parse(Object.fromEntries(formData));const context=await requireTenantContext();await getDatabase().transaction(async tx=>{const[request]=await tx.insert(serviceRequests).values({organizationId:context.organizationId,orderId:id,warrantyItemId:data.warrantyItemId||null,title:data.title,description:data.description}).returning({id:serviceRequests.id});await tx.update(orders).set({stage:"service"}).where(and(eq(orders.organizationId,context.organizationId),eq(orders.id,id)));await tx.insert(activityEvents).values({organizationId:context.organizationId,orderId:id,actorType:"user",actorUserId:context.userId,eventType:"service_request_opened",entityType:"service_request",entityId:request?.id,metadataJson:{title:data.title}})});revalidatePath(`/app/orders/${id}`);revalidatePath("/app/service");}

export async function updateServiceStatusAction(formData:FormData){const requestId=z.uuid().parse(formData.get("requestId"));const status=z.enum(["open","in_progress","resolved","closed"]).parse(formData.get("status"));const context=await requireTenantContext();await getDatabase().update(serviceRequests).set({status,resolvedAt:["resolved","closed"].includes(status)?new Date():null}).where(and(eq(serviceRequests.organizationId,context.organizationId),eq(serviceRequests.id,requestId)));revalidatePath("/app/service");}
